export const COMMON_URL = `${process.env.APPLICATION_BFF_URL}`;
export const REQUEST_ADDRESS_FROM_ZIP = 'REQUEST_ADDRESS_FROM_ZIP';
export const RECEIVED_ADDRESS_FROM_ZIP_ERROR = 'RECEIVED_ADDRESS_FROM_ZIP_ERROR';
export const RECEIVED_ADDRESS_FROM_ZIP = 'RECEIVED_ADDRESS_FROM_ZIP';
