export const HEADER_TOGGLE_CAT = 'HEADER_TOGGLE_CAT';
export const HEADER_SHOW_HOME_PAGE = 'HEADER_SHOW_HOME_PAGE';
export const HEADER_SHOW_LEFT_BACK_BUTTON = 'HEADER_SHOW_LEFT_BACK_BUTTON';
export const HEADER_HIDE_LEFT_BACK_BUTTON = 'HEADER_HIDE_LEFT_BACK_BUTTON';
export const HEADER_ORDER_HISTORY_OPEN = 'HEADER_ORDER_HISTORY_OPEN';
export const HEADER_SEARCH_PRODUCT = 'HEADER_SEARCH_PRODUCT';
export const HEADER_SCAN_PRODUCT = 'HEADER_SCAN_PRODUCT';
export const HEADER_REFRESH_PRODUCT = 'HEADER_REFRESH_PRODUCT';
export const HEADER_SET_REFRESH_TIME = 'HEADER_SET_REFRESH_TIME';
export const HEADER_ONHOLD_HISTORY_OPEN = 'HEADER_ONHOLD_HISTORY_OPEN';
export const HEADER_ADD_MISC_PRODUCT = 'HEADER_ADD_MISC_PRODUCT';

