//urls

export const ADD_INVOICE_LOOKUP = `${process.env.APPLICATION_BFF_URL}/accounts/invoice`;

export const INVOICE_SEARCH_LOOKUP =`${process.env.APPLICATION_BFF_URL}/accounts/invoice/search`;

//constants

export const REQUEST_LOOKUPS_FOR_INVOICE_SEARCH = 'REQUEST_LOOKUPS_FOR_INVOICE_SEARCH';
export const RECEIVED_LOOKUPS_FOR_INVOICE_SEARCH= 'RECEIVED_LOOKUPS_FOR_INVOICE_SEARCH';

export const REQUEST_INVOICE_SEARCH_RESULT = 'REQUEST_INVOICE_SEARCH_RESULT';
export const RECEIVED_INVOICE_SEARCH_RESULT = 'RECEIVED_INVOICE_SEARCH_RESULT';

export const REQUEST_LOOKUPS_FOR_NEW_INVOICE = 'REQUEST_LOOKUPS_FOR_NEW_INVOICE';
export const RECEIVED_LOOKUPS_FOR_NEW_INVOICE = 'RECEIVED_LOOKUPS_FOR_NEW_INVOICE';

export const REQUEST_SUPPLIER_SITES_FOR_INVOICE ='REQUEST_SUPPLIER_SITES_FOR_INVOICE';
export const RECEIVED_SUPPLIER_SITES_FOR_INVOICE = 'RECEIVED_SUPPLIER_SITES_FOR_INVOICE';

export const REQUEST_EDIT_INVOICE_DATA = 'REQUEST_EDIT_INVOICE_DATA';
export const RECEIVED_EDIT_INVOICE_DATA = 'RECEIVED_EDIT_INVOICE_DATA';

export const REQUEST_FOR_INVOICE_BLOCK_CHAIN_HISTORY = 'REQUEST_FOR_INVOICE_BLOCK_CHAIN_HISTORY';
export const RECEIVED_FOR_INVOICE_BLOCK_CHAIN_HISTORY = 'RECEIVED_FOR_INVOICE_BLOCK_CHAIN_HISTORY';

export const INVOICE_REG_FORM_RESPONSE = 'INVOICE_REG_FORM_RESPONSE';
export const INVOICE_REG_FORM_REQUEST = 'INVOICE_REG_FORM_REQUEST';


export const REQUEST_INVOICE_VIEW_PAGE_BY_INVOICE_NUMBER = 'REQUEST_INVOICE_VIEW_PAGE_BY_INVOICE_NUMBER'; 
export const RECEIVED_INVOICE_VIEW_PAGE_BY_INVOICE_NUMBER = 'RECEIVED_INVOICE_VIEW_PAGE_BY_INVOICE_NUMBER';

export const REQUEST_INVOICE_STATUS_UPDATE = 'REQUEST_INVOICE_STATUS_UPDATE';
export const RECEIVED_INVOICE_STATUS_UPDATE = 'RECEIVED_INVOICE_STATUS_UPDATE';