/* STRAT :: API Constants */

export const ITEM_SEARCH_URL = `${process.env.APPLICATION_BFF_URL}/items/search`;

export const ADD_NEW_ITEM_PAGE_URL = `${process.env.APPLICATION_BFF_URL}/items`;

export const POST_ITEM_SEARCH_DATA_URL = `${process.env.APPLICATION_BFF_URL}/items/search`;



/* Start Item master page constants */

export const REQUEST_ITEM_SEARCH = 'REQUEST_ITEM_SEARCH';
export const RECEIVED_ITEM_SEARCH = 'RECEIVED_ITEM_SEARCH';
export const RECEIVED_ITEM_SEARCH_ERROR = 'RECEIVED_ITEM_SEARCH_ERROR';

export const REQUEST_ADD_NEW_ITEM_PAGE = 'REQUEST_ADD_NEW_ITEM_PAGE';
export const RECEIVED_ADD_NEW_ITEM_PAGE = 'RECEIVED_ADD_NEW_ITEM_PAGE';
export const RECEIVED_ADD_NEW_ITEM_PAGE_ERROR = 'RECEIVED_ADD_NEW_ITEM_PAGE_ERROR';

export const ITEM_REG_FORM_REQUEST = 'ITEM_REG_FORM_REQUEST';
export const ITEM_REG_FORM_RESPONSE = 'ITEM_REG_FORM_RESPONSE';
export const ITEM_REG_FORM_RESPONSE_ERROR = 'ITEM_REG_FORM_RESPONSE_ERROR';

/* End Item master page constants */

// ITEM TYPE CONSTANTS

export const REQUEST_ITEM_TYPE = 'REQUEST_ITEM_TYPE';
export const RECEIVED_ITEM_TYPE = 'RECEIVED_ITEM_TYPE';
export const RECEIVED_ITEM_TYPE_ERROR = 'RECEIVED_ITEM_TYPE_ERROR';

// Item Search Page Post Data 

export const REQUEST_POST_ITEM_SEARCH_DATA = 'REQUEST_POST_ITEM_SEARCH_DATA';
export const RECEIVED_POST_ITEM_SEARCH_DATA = 'RECEIVED_POST_ITEM_SEARCH_DATA';
export const RECEIVED_POST_ITEM_SEARCH_DATA_ERROR = 'RECEIVED_POST_ITEM_SEARCH_DATA_ERROR';

//  Item View Page by Clicking Item No on Search Paga table

export const REQUEST_ITEM_VIEW_PAGE_BY_ITEM_NUMBER = 'REQUEST_ITEM_VIEW_PAGE_BY_ITEM_NUMBER';
export const RECEIVED_ITEM_VIEW_PAGE_BY_ITEM_NUMBER = 'RECEIVED_ITEM_VIEW_PAGE_BY_ITEM_NUMBER';
export const RECEIVED_ITEM_VIEW_PAGE_BY_ITEM_NUMBER_ERROR = 'RECEIVED_ITEM_VIEW_PAGE_BY_ITEM_NUMBER_ERROR';


// CONSTANT ITEM BLOCK CHAIN HISTORY FOR ITEM

export const REQUEST_FOR_ITEM_BLOCK_CHAIN_HISTORY = 'REQUEST_FOR_ITEM_BLOCK_CHAIN_HISTORY';
export const RECEIVED_FOR_ITEM_BLOCK_CHAIN_HISTORY = 'RECEIVED_FOR_ITEM_BLOCK_CHAIN_HISTORY';
export const RECEIVED_FOR_ITEM_BLOCK_CHAIN_HISTORY_ERROR = 'RECEIVED_FOR_ITEM_BLOCK_CHAIN_HISTORY_ERROR';


// CONSTANT FOR EDIT ITEM DATA

export const REQUEST_ITEM_EDIT_DATA = 'REQUEST_ITEM_EDIT_DATA';
export const RECEIVED_ITEM_EDIT_DATA = 'RECEIVED_ITEM_EDIT_DATA';
export const RECEIVED_ITEM_EDIT_DATA_ERROR = 'RECEIVED_ITEM_EDIT_DATA_ERROR';

// CONSTANT FOR UN ASSIGN A ORGANIZATION FOR ITEM

export const REQUEST_FOR_UNASSIGN_A_ORGANIZATION = 'REQUEST_FOR_UNASSIGN_A_ORGANIZATION';
export const RECEIVED_FOR_UNASSIGN_A_ORGANIZATION = 'RECEIVED_FOR_UNASSIGN_A_ORGANIZATION';
export const RECEIVED_FOR_UNASSIGN_A_ORGANIZATION_ERROR = 'RECEIVED_FOR_UNASSIGN_A_ORGANIZATION_ERROR';

// CONSTANT FOR ASSIGN ORGANISATION TO ITEMS

export const REQUEST_FOR_ASSIGN_ORG_TO_ITEMS = 'REQUEST_FOR_ASSIGN_ORG_TO_ITEMS';
export const RECEIVED_FOR_ASSIGN_ORG_TO_ITEMS = 'RECEIVED_FOR_ASSIGN_ORG_TO_ITEMS';
export const RECEIVED_FOR_ASSIGN_ORG_TO_ITEMS_ERROR = 'RECEIVED_FOR_ASSIGN_ORG_TO_ITEMS_ERROR';


//constants for clearing item status code 

export const REQUEST_ITEM_CODE_STATUS_CLEAR = 'REQUEST_ITEM_CODE_STATUS_CLEAR'