// LOT Module Endpoints
export const LOT_LOOKUP_URL = `${process.env.APPLICATION_BFF_URL}/lots/addform`;
// "http://divine-feather-4140.getsandbox.com/lot/add";
// `${process.env.APPLICATION_BFF_URL}/lot/addform`;
export const LOT_SEARCH_URL = `${process.env.APPLICATION_BFF_URL}/lots/search`;
export const LOT_SAVE_URL = `${process.env.APPLICATION_BFF_URL}/lots/addform`;
// "http://divine-feather-4140.getsandbox.com/lot/saveLot";
// `${process.env.APPLICATION_BFF_URL}/lot/search`;

// LOT Module Constants
export const RENDER_ADD_NEW_LOT= 'RENDER_ADD_NEW_LOT';
export const REQUEST_LOT_LOOKUP_DATA = 'REQUEST_LOT_LOOKUP_DATA';
export const RECEIVED_LOT_LOOKUP_DATA_SUCCESS = 'RECEIVED_LOT_LOOKUP_DATA_SUCCESS';
export const RECEIVED_LOT_LOOKUP_DATA_ERROR = 'RECEIVED_LOT_LOOKUP_DATA_ERROR';
export const REQUEST_SUBINVENTORY_BY_ORGANIZATION = 'REQUEST_SUBINVENTORY_BY_ORGANIZATION';
export const RECEIVE_SUBINVENTORY_BY_ORGANIZATION = 'RECEIVE_SUBINVENTORY_BY_ORGANIZATION';

export const REQUEST_ORGANIZATION_BY_ITEM = 'REQUEST_ORGANIZATION_BY_ITEM';
export const RECEIVE_ORGANIZATION_BY_ITEM = 'RECEIVE_ORGANIZATION_BY_ITEM';

export const RECEIVE_LOT_DATA = 'RECEIVE_LOT_DATA';
export const REQUEST_LOT_DATA = 'REQUEST_LOT_DATA';
export const RECEIVE_LOT_DATA_ERROR = 'RECEIVE_LOT_DATA_ERROR';

export const REQUEST_LOT_SEARCH_DATA = 'REQUEST_LOT_SEARCH_DATA';
export const RECEIVE_LOT_SEARCH_DATA = 'RECEIVE_LOT_SEARCH_DATA';
export const REQUEST_LOT_DATA_BY_LOT_NAME = 'REQUEST_LOT_DATA_BY_LOT_NAME';
export const RECEIVE_LOT_DATA_BY_LOT_NAME = 'RECEIVE_LOT_DATA_BY_LOT_NAME';

export const REQUEST_ITEMNAME_BY_ITEMTYPE = 'REQUEST_ITEMNAME_BY_ITEMTYPE';
export const RECEIVE_ITEMNAME_BY_ITEMTYPE = 'RECEIVE_ITEMNAME_BY_ITEMTYPE';
