export const ORDERHISTORY_URL = `${process.env.APPLICATION_BFF_URL}`;
export const REQUEST_ORDERHISTORY = 'REQUEST_ORDERHISTORY';
export const RECEIVED_ORDERHISTORY = 'RECEIVED_ORDERHISTORY';
export const RECEIVED_ORDERHISTORY_ERROR = 'RECEIVED_ORDERHISTORY_ERROR';

export const REQUEST_ORDERHISTORY_DATA = 'REQUEST_ORDERHISTORY_DATA';
export const RECEIVED_ORDERHISTORY_DATA = 'RECEIVED_ORDERHISTORY_DATA';
export const RECEIVED_ORDERHISTORY_DATA_ERROR = 'RECEIVED_ORDERHISTORY_DATA_ERROR';

export const REQUEST_ORDERHISTORY_CLEAR = 'REQUEST_ORDERHISTORY_CLEAR';