// ORGANIZATION MODULE CONSTANTS

export const ORGANIZATION_ADD_FORM_URL = `${process.env.APPLICATION_BFF_URL}/organization/addform`;
export const ORGANIZATION_SEARCH_URL = `${process.env.APPLICATION_BFF_URL}/organization/search`;
export const ORGANIZATION_BLOCKCHAIN_HISTORY_URL = `${process.env.APPLICATION_BFF_URL}/organization/history`;

export const REQUEST_ORGANIZATION_ADD_FORM = 'REQUEST_ORGANIZATION_ADD_FORM';
export const RECEIVED_ORGANIZATION_ADD_FORM = 'RECEIVED_ORGANIZATION_ADD_FORM';
export const RECEIVED_ORGANIZATION_ADD_FORM_ERROR = 'RECEIVED_ORGANIZATION_ADD_FORM_ERROR';

export const REQUEST_ORGANIZATION_INFO_DATA = 'REQUEST_ORGANIZATION_INFO_DATA';
export const RECEIVED_ORGANIZATION_INFO_DATA = 'RECEIVED_ORGANIZATION_INFO_DATA';
export const RECEIVED_ORGANIZATION_INFO_DATA_ERROR = 'RECEIVED_ORGANIZATION_INFO_DATA_ERROR';

export const REQUEST_STATE_DATA_BY_COUNTYID = 'REQUEST_STATE_DATA_BY_COUNTYID';
export const RECEIVED_STATE_DATA_BY_COUNTYID = 'RECEIVED_STATE_DATA_BY_COUNTYID';
export const RECEIVED_STATE_DATA_BY_COUNTYID_FOR_CONTACT_ADDRESS =
    'RECEIVED_STATE_DATA_BY_COUNTYID_FOR_CONTACT_ADDRESS';
export const RECEIVED_STATE_DATA_BY_COUNTYID_ERROR = 'RECEIVED_STATE_DATA_BY_COUNTYID_ERROR';

export const REQUEST_ORGANIZATION_SEARCH_RESULT_DATA = 'REQUEST_ORGANIZATION_SEARCH_RESULT_DATA';
export const RECEIVED_ORGANIZATION_SEARCH_RESULT_DATA = 'RECEIVED_ORGANIZATION_SEARCH_RESULT_DATA';
export const RECEIVED_ORGANIZATION_SEARCH_RESULT_DATA_ERROR =
    'RECEIVED_ORGANIZATION_SEARCH_RESULT_DATA_ERROR';

export const REQUEST_ORGANIZATION_BLOCKCHAIN_HISTORY_DATA = 'REQUEST_ORGANIZATION_BLOCKCHAIN_HISTORY_DATA';
export const RECEIVED_ORGANIZATION_BLOCKCHAIN_HISTORY_DATA =
    'RECEIVED_ORGANIZATION_BLOCKCHAIN_HISTORY_DATA';
export const RECEIVED_ORGANIZATION_BLOCKCHAIN_HISTORY_DATA_ERROR =
    'RECEIVED_ORGANIZATION_BLOCKCHAIN_HISTORY_DATA_ERROR';

export const REQUEST_ORGANIZATION_VIEW_DATA = 'REQUEST_ORGANIZATION_VIEW_DATA';
export const RECEIVED_ORGANIZATION_VIEW_DATA = 'RECEIVED_ORGANIZATION_VIEW_DATA';
export const RECEIVED_ORGANIZATION_VIEW_DATA_ERROR = 'RECEIVED_ORGANIZATION_VIEW_DATA_ERROR';

export const REQUEST_ORGANIZATION_EDIT_DATA = 'REQUEST_ORGANIZATION_EDIT_DATA';
export const RECEIVED_ORGANIZATION_EDIT_DATA = 'RECEIVED_ORGANIZATION_EDIT_DATA';
export const RECEIVED_ORGANIZATION_EDIT_DATA_ERROR = 'RECEIVED_ORGANIZATION_EDIT_DATA_ERROR';