export const USER_ROLE_URL = `${process.env.APPLICATION_BFF_URL}/users/authenticate`;
export const REQUEST_USER_ROLE = 'REQUEST_USER_ROLE';
export const RECEIVED_USER_ROLE = 'RECEIVED_USER_ROLE';
export const RECEIVED_USER_ROLE_ERROR = 'RECEIVED_USER_ROLE_ERROR';